from django.urls import path
from inicio.views import (
    inicio, 
    crear_juego, 
    crear_consola, 
    crear_empresa, 
    lista_juegos, 
    lista_consolas, 
    lista_empresas,
    buscar_juego,
    buscar_consola,
    buscar_empresa,
    VerEmpresa,
    ActualizarEmpresa, 
    EliminarEmpresa,
    VerJuego,             
    ActualizarJuego,
    EliminarJuego,
    VerConsola,           
    ActualizarConsola,
    EliminarConsola,
)
urlpatterns = [
    path('', inicio, name='inicio'),
    path('crear-juego/', crear_juego, name='crear_juego'),
    path('crear-consola/', crear_consola, name='crear_consola'),
    path('crear-empresa/', crear_empresa, name='crear_empresa'),
    path('lista-juegos/', lista_juegos, name='lista_juegos'),
    path('lista-consolas/', lista_consolas, name='lista_consolas'),
    path('lista-empresas/', lista_empresas, name='lista_empresas'),
    path('buscar-juego/', buscar_juego, name='buscar_juego'),
    path('buscar-consola/', buscar_consola, name='buscar_consola'),
    path('buscar-empresa/', buscar_empresa, name='buscar_empresa'),
    path('ver-empresa/<int:pk>/', VerEmpresa.as_view(), name='ver_empresa'),
    path('actualizar-empresa/<int:pk>/', ActualizarEmpresa.as_view(), name='actualizar_empresa'),
    path('eliminar-empresa/<int:pk>/', EliminarEmpresa.as_view(), name='eliminar_empresa'),
    path('ver-juego/<int:pk>/', VerJuego.as_view(), name='ver_juego'),
    path('actualizar-juego/<int:pk>/', ActualizarJuego.as_view(), name='actualizar_juego'),
    path('eliminar-juego/<int:pk>/', EliminarJuego.as_view(), name='eliminar_juego'),
    path('ver-consola/<int:pk>/', VerConsola.as_view(), name='ver_consola'),
    path('actualizar-consola/<int:pk>/', ActualizarConsola.as_view(), name='actualizar_consola'),
    path('eliminar-consola/<int:pk>/', EliminarConsola.as_view(), name='eliminar_consola'),
]