# Generated by Django 5.2.8 on 2025-11-11 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juego',
            old_name='jugadores',
            new_name='cant_jugadores',
        ),
    ]
