# Generated by Django 5.2.8 on 2025-11-11 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_rename_jugadores_juego_cant_jugadores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='cant_jugadores',
        ),
    ]
