# Generated by Django 5.2.8 on 2025-11-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_consola_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='image',
            field=models.ImageField(null=True, upload_to='imagenes_juegos'),
        ),
    ]
