# Generated by Django 5.2.8 on 2025-11-28 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_juego_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juego',
            old_name='image',
            new_name='imagen',
        ),
    ]
